### ISSUE TITLE
ready for launch

### ISSUE THREAD

**Issue by katieannemills** [swcarpentry/SWC-bug-bbq#1]
Hi @ttimbers - alright, [website is live](http://swcarpentry.github.io/SWC-bug-bbq/) and your blog post has the right links plugged in at [this copy](https://github.com/swcarpentry/SWC-bug-bbq/blob/gh-pages/blog_post/bug_bbq_blog_post.md). Would you please fire off a PR with your blog post to the blog?

Once that blog post is live, @weaverbel can you book some tweets for us from swcarpentry's twitter? Thanks all - and be sure to push this hard on social media for the next month. I'd like to get some comments on the upcoming community call May 10 too, if @ttimbers or @gvwilson is free!

**Comment by ttimbers** [comment]
PR of blog post is sent to SWC website repo.  I'll help push this on twitter, and I can make the first community call on May 10th.

**Comment by ttimbers** [comment]
blog post is live & I've started tweeting. Can you send me a link to the lab meeting etherpad?

**Comment by katieannemills** [comment]
Thanks, @ttimbers! lab meeting etherpad: http://pad.software-carpentry.org/swc-lab-meeting-2016-05-10

**Comment by ttimbers** [comment]
I've also sent out an email to the discuss list.
