### ISSUE TITLE
Where are we getting names/affiliations of contributors from for DOI?

### ISSUE THREAD

**Issue by ttimbers** [swcarpentry/SWC-bug-bbq#10]
This question was emailed to me today, as the person wants to ensure the correct name and affiliation gets attributed.

**Comment by katieannemills** [comment]
Zenodo + github pull author info from the repo's contributor list _I think_; @gvwilson, thoughts / policy?

**Comment by wking** [comment]
On Tue, May 10, 2016 at 11:33:35AM -0700, Bill Mills wrote:

> Zenodo + github pull author info from the repo's contributor list _I
> think_; @gvwilson, thoughts / policy?

The most recent discussion I've seen on this point is here [1](https://github.com/gvwilson/new-lesson-example/pull/15#discussion_r60996304).  I
think Git-commit author information is a safe bet.  We also want to
credit non-commit contribution, but the categorization and tooling
behind such credits are unclear.
