### ISSUE TITLE
BBQ Meet Up at University of Michigan

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/SWC-bug-bbq#11]
The U of M continent will be meeting up on the 7th floor UM School of Public Health I, at 1415 Washington Heights in Ann Arbor, MI. We haven't nailed down a time window yet, but I'll update the issue when I know. Any locals that aren't on the U of M SWC mailing list should feel free to ping me to let me know if you're coming. We should have 6 or 7 U of M people attending

**Comment by katieannemills** [comment]
Thanks, @pschloss - you're on the map! Let me know when you have a time and I'll update your pin, and anything else I can do to support.

**Comment by pschloss** [comment]
Thanks - well be going from 12 to 5 eastern
