### ISSUE TITLE
BBQ Meetup at the University of St Andrews

### ISSUE THREAD

**Issue by olexandr-konovalov** [swcarpentry/SWC-bug-bbq#12]
I suggest to add another pin on the map: School of Computer Science, University of St Andrews (please see the location at http://www.cs.st-andrews.ac.uk/contact_details), room 1.04 from 10am till 4pm (except the lunch break 1pm-2pm). The minimal plan is to work on the GAP lesson among the "elective lessons", but dependently on the quorum we may try more, and also this will be a chance of colleagues from other departments to come and learn more about Software Carpentry.

**Comment by katieannemills** [comment]
Done! And great idea to combo this with an open house for people to come learn about Software Carpentry; we're doing the same in Vancouver, and I think it's a great opportunity. Let us know anything we can do to support!

**Comment by olexandr-konovalov** [comment]
Status update: all issues from https://github.com/alex-konovalov/gap-lesson/milestones/1.0 milestone closed!

**Comment by katieannemills** [comment]
Excellent work! Care to add a time of completion to the BBQ website? Thanks much.

**Comment by olexandr-konovalov** [comment]
done, thanks!

**Comment by gvwilson** [comment]
@BillMills close this?
