### ISSUE TITLE
SWC BBQ at EITN in Paris (France)

### ISSUE THREAD

**Issue by mstimberg** [swcarpentry/SWC-bug-bbq#13]
We are bit late to the party, but a few SWC instructors from the Paris area will get together at the European Institute for Theoretical Neuroscience (EITN) to participate in the bug BBQ

Where: EITN, 74 Rue du Faubourg Saint-Antoine, 75012 Paris, France (https://www.openstreetmap.org/?mlat=48.851667&mlon=2.374022&zoom=16#map=16/48.8517/2.3740)
When: 6pm – 9pm (local time, i.e. 4pm – 7pm UTC)

We'll have a look at SWC standard lessons mostly (bash, git, python), but potentially also at some website issues.

**Comment by katieannemills** [comment]
Awesome, thanks for getting involved @mstimberg! You're on the map; let us know anything we can do to assist.

**Comment by gvwilson** [comment]
@BillMills close this?
