### ISSUE TITLE
Suggested workflow

### ISSUE THREAD

**Issue by pschloss** [swcarpentry/SWC-bug-bbq#14]
The U of Michigan group (~5-7 people) is going to be working together from noon to 5 today (eastern). We're going to start with an overview of making pull requests to submit materials. Is there a suggested workflow for claiming an issue, working on it, and making the pull request?

**Comment by gvwilson** [comment]
Best way to claim an issue is to add a line to the Etherpad associated 
with that repository on http://swcarpentry.github.io/SWC-bug-bbq/ - I'll 
be online by 11:00 to chat with anyone who wants to.  (And apologies for 
the mailing list outage - we're working on it.)

**Comment by gvwilson** [comment]
@BillMills close this?
