### ISSUE TITLE
UCONN Bug BBQ

### ISSUE THREAD

**Issue by tem11010** [swcarpentry/SWC-bug-bbq#16]
Some of will be hosting Bug BBQ here at UCONN, Connecticut.

Where: Torrey Life Sciences Building, Rm 363, Storrs, CT. 06269
(https://www.openstreetmap.org/?mlat=41.8097433&mlon=-72.2554618&zoom=16#map=16/41.8097/-72.2555)

When: 10.30 - 13.30

We'll be working mostly on R and SQL lessons.

**Comment by katieannemills** [comment]
Welcome aboard, you're on the map! Let us know anything we can do to support.

**Comment by tem11010** [comment]
Hi Bill. 
Great! There's not too much information in the etherpads at the moment. Any suggestions on what to focus on?

**Comment by katieannemills** [comment]
@tem11010 yeah, we set up etherpads for the maintainers to use at their discretion, so if you don't see anything there, the place to dive in is the milestone link - every lesson should have issues posted there that need to get done; if any of them are unclear, don't hesitate to respond to the thread and ask for the maintainer's guidance.

**Comment by gvwilson** [comment]
@BillMills close this?
