### ISSUE TITLE
add etherpad links to site pins?

### ISSUE THREAD

**Issue by ttimbers** [swcarpentry/SWC-bug-bbq#4]
When I click on the Vancouver site pin on the map I get sent to a new page that says:

```
Cannot GET /swc-instructor-retreat-2015-vancouver
```

Should we have a very simple etherpad (perhaps based off last years SWC retreat) that gets linked to for each site?

**Comment by katieannemills** [comment]
I was just going to put address and room numbers in the pins, no need to link to anything - unless you think it's critical?

**Comment by ttimbers** [comment]
sure, that's great!
