### ISSUE TITLE
Adding contributed lessons to the agenda

### ISSUE THREAD

**Issue by olexandr-konovalov** [swcarpentry/SWC-bug-bbq#5]
I would like to suggest some other activities extending the scope of the BBQ beyond the core Software Carpentry lessons.

Namely, I am interested to work on GAP and SageMath Software Carpentry lessons (see
http://software-carpentry.org/blog/2016/02/new-lesson-on-gap.html). These lessons are at different stages (GAP was taught once in November 2015, while SageMath is yet at the early planning stage and needs a lesson outline).

As far as I understand the idea of the BBQ is to publish the next version of the lessons, and I think that the GAP lesson is quite close to a state when it can be published. I was going to ask for an advise on versioning, when the BBQ announcement came. My understanding is that because it is a contributed lesson and not one of the core lessons, at least at the current stage it should be published independently and use own version numbers - am I right? But even in this case, I think that colocating this activity with the BBQ and publishing the lesson simultaneously would be great and could help to attract new contributors to this lesson.

For the SageMath, we could try to plan some collaborative activity to establish lesson outline and kick-off the actual writing up of the lesson.

**Comment by ttimbers** [comment]
I would like to add the Docker lesson that @HeidiSeibold, @BillMills, @lmguzman, @Emaasit, @cboettig  and I started at ROpenSci. The repo for that lesson lives [here](https://github.com/ropenscilabs/r-docker-tutorial).

@BillMills for these contributor lessons, should we make up our own etherpads and create milestones too?

**Comment by katieannemills** [comment]
Hi team,

Yes! All these projects are great fits at the BBQ; I will put pointers to them on the website tonight. To your questions:
- @alex-konovalov: I'm not sure how new lessons pick up version numbers; none of the r lessons, for example, have been present since 1.0 (I think). @gvwilson, is there a policy for version numbers for new lessons?
- @ttimbers: I'll wrangle the etherpad, but yes please make issues & a milestone! Once you have a milestone, please post the link in this issue and I'll put it on the website.

**Comment by gvwilson** [comment]
We only assign version numbers to our core lessons - contributed lessons 
can be numbered as their authors choose.

**Comment by olexandr-konovalov** [comment]
@gvwilson: thanks, that makes perfect sense. @BillMills thank you for adding the link to the website and setting up the etherpad. I've now created 1.0 milestone so please update the link to https://github.com/alex-konovalov/gap-lesson/milestones/1.0

**Comment by katieannemills** [comment]
@alex-konovalov linked - thanks for jumping in!
