### ISSUE TITLE
Woods Hole BBQ

### ISSUE THREAD

**Issue by raynamharris** [swcarpentry/SWC-bug-bbq#8]
I would host a bbq in Woods Hole, MA. I can pick a room later depending on the size of the group. Please put Loeb Building 7 Mbl St, Woods Hole, MA on the map.

**Comment by katieannemills** [comment]
awesome, the map doesn't just autozoom on UBC now - speaking of, @weaverbel, any Australian BBQ'ers? pinning Vancouver and Brisbane pegs the map as worldwide :)

**Comment by katieannemills** [comment]
oh also @raynamharris - what hours would you like to run for?

**Comment by raynamharris** [comment]
Let's go with 1 pm to 11 pm Eastern

On Tue, May 10, 2016 at 1:12 PM, Bill Mills notifications@github.com
wrote:

> oh also @raynamharris https://github.com/raynamharris - what hours
> would you like to run for?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/SWC-bug-bbq/issues/8#issuecomment-218242947

## 

Rayna M. Harris
Graduate Student, Hans Hofmann Lab  http://cichlid.biosci.utexas.edu/
​Training & Outreach Coordinator, Center for Computational Biology and
Bioinformatics http://ccbb.biosci.utexas.edu/
  http://ccbb.biosci.utexas.edu/
The University of Texas at Austin
raynamharris.github.io
​@raynamharris​ https://twitter.com/raynamharris

**Comment by weaverbel** [comment]
@BillMills Might be a hard sell ten days after the MozSprint, but will see what I can do after I get home on Saturday - I might ping the Canberra guys who wanted to develop the molecular biology Python lesson and see if they are keen to work on the existing stuff.
